[package]
name = "stipe"
version = "0.1.0"
authors = ["blobject <agaric@pm.me>"]
edition = "2021"

[dependencies]
actix-files = "0.5"
actix-web = "3"
ammonia = "3"
chrono = "0.4"
pulldown-cmark = { version = "0.9", default-features = false }
rand = "0.8"
regex = "1"
